/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bailamthemLab2.javaSwing;

import javax.swing.JOptionPane;

/**
 *
 * @author HL COMPUTER
 */
public class lesson3 extends javax.swing.JFrame {

    /**
     * Creates new form lesson3
     */
    public lesson3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtB = new javax.swing.JTextField();
        txtA = new javax.swing.JTextField();
        btnGiaiPt = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtKq = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPt = new javax.swing.JTextField();
        btnResert = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(160, 229, 227));
        setMinimumSize(new java.awt.Dimension(700, 550));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Harrington", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(25, 130, 210));
        jLabel1.setText("Giai phuong trình bac 1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 430, -1));

        jLabel2.setFont(new java.awt.Font("Consolas", 2, 20)); // NOI18N
        jLabel2.setText("Nhập B");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, 40));

        jLabel3.setFont(new java.awt.Font("Consolas", 2, 20)); // NOI18N
        jLabel3.setText("Nhập A");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 80, 40));

        txtB.setBackground(new java.awt.Color(231, 231, 235));
        txtB.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtB.setToolTipText("");
        txtB.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(231, 231, 235), new java.awt.Color(231, 231, 235)));
        txtB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBActionPerformed(evt);
            }
        });
        getContentPane().add(txtB, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 210, 30));

        txtA.setBackground(new java.awt.Color(231, 231, 235));
        txtA.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtA.setToolTipText("");
        txtA.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(231, 231, 235), new java.awt.Color(231, 231, 235)));
        txtA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAActionPerformed(evt);
            }
        });
        getContentPane().add(txtA, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 210, 30));

        btnGiaiPt.setBackground(new java.awt.Color(224, 204, 245));
        btnGiaiPt.setFont(new java.awt.Font("Calibri Light", 3, 21)); // NOI18N
        btnGiaiPt.setForeground(new java.awt.Color(0, 102, 255));
        btnGiaiPt.setText("Giải phương trình");
        btnGiaiPt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(224, 204, 245), new java.awt.Color(224, 204, 245), new java.awt.Color(224, 204, 245), new java.awt.Color(224, 204, 245)));
        btnGiaiPt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGiaiPtActionPerformed(evt);
            }
        });
        getContentPane().add(btnGiaiPt, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 230, 40));

        jLabel4.setFont(new java.awt.Font("Consolas", 2, 20)); // NOI18N
        jLabel4.setText("Kết quả");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, -1, 40));

        txtKq.setBackground(new java.awt.Color(231, 231, 235));
        txtKq.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtKq.setToolTipText("");
        txtKq.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(231, 231, 235), new java.awt.Color(231, 231, 235)));
        txtKq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKqActionPerformed(evt);
            }
        });
        getContentPane().add(txtKq, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 330, 40));

        jLabel5.setFont(new java.awt.Font("Consolas", 2, 20)); // NOI18N
        jLabel5.setText("Phường trình");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, 40));

        txtPt.setBackground(new java.awt.Color(231, 231, 235));
        txtPt.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtPt.setToolTipText("");
        txtPt.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(231, 231, 235), new java.awt.Color(231, 231, 235)));
        txtPt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPtActionPerformed(evt);
            }
        });
        getContentPane().add(txtPt, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 330, 30));

        btnResert.setBackground(new java.awt.Color(255, 204, 204));
        btnResert.setFont(new java.awt.Font("Calibri Light", 3, 18)); // NOI18N
        btnResert.setText("Reset");
        btnResert.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 204, 204), new java.awt.Color(255, 204, 204), new java.awt.Color(255, 204, 204), new java.awt.Color(255, 204, 204)));
        btnResert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResertActionPerformed(evt);
            }
        });
        getContentPane().add(btnResert, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 370, 90, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBActionPerformed

    }//GEN-LAST:event_txtBActionPerformed

    private void txtAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAActionPerformed

    private void btnGiaiPtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGiaiPtActionPerformed
           String numberA = txtA.getText();
           String numberB = txtB.getText();
           
           
         String checkNumber = "(\\d{1,50}\\.\\d{1,50})";
    
           if(numberA.isEmpty() || numberB.isEmpty()){
                   JOptionPane.showMessageDialog(this, "Hãy nhập dữ liệu !","thông báo",JOptionPane.ERROR_MESSAGE);
           }else if(!numberA.matches(checkNumber) || !numberB.matches(checkNumber)){
                    JOptionPane.showMessageDialog(this, "Hãy nhập số thực !","thông báo",JOptionPane.ERROR_MESSAGE);
            }else{
                    double a = Double.valueOf(numberA) ;
                    double  b = Double.valueOf(numberB) ;
                      if( a == 0){
                                if(b == 0){
                                        JOptionPane.showMessageDialog(this, "Phương trình có vô số nghiệm !","thông báo",JOptionPane.WARNING_MESSAGE);
                                }else{
                                       JOptionPane.showMessageDialog(this, "Phương trình vô nghiệm !","thông báo",JOptionPane.WARNING_MESSAGE);
                                }
                                               
                       }else{
                                  JOptionPane.showMessageDialog(this, "Phương trình có 1 nghiệm duy nhất !","thông báo",JOptionPane.INFORMATION_MESSAGE);
                                  double  kq = -b / a;
                              
                                  txtPt.setText(numberA + "x" + " + "+numberB);
                                  txtKq.setText(String.valueOf(String.format("%.2f", kq)));                         
                         }
            }
           
    }//GEN-LAST:event_btnGiaiPtActionPerformed

    private void txtKqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKqActionPerformed

    private void txtPtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPtActionPerformed

    private void btnResertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResertActionPerformed
        txtA.setText("");
        txtB.setText("");
        txtKq.setText("");
        txtPt.setText("");
    }//GEN-LAST:event_btnResertActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lesson3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lesson3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lesson3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lesson3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lesson3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGiaiPt;
    private javax.swing.JButton btnResert;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtA;
    private javax.swing.JTextField txtB;
    private javax.swing.JTextField txtKq;
    private javax.swing.JTextField txtPt;
    // End of variables declaration//GEN-END:variables
}
