/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bailamthemLab2.javaSwing;

import javax.swing.JOptionPane;

/**
 *
 * @author HL COMPUTER
 */
public class lesson4 extends javax.swing.JFrame {

    /**
     * Creates new form lesson4
     */
    public lesson4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtC = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtKq = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtA = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtB = new javax.swing.JTextField();
        btnKq = new javax.swing.JButton();
        btnResert = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(160, 229, 227));
        setMinimumSize(new java.awt.Dimension(750, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Harrington", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(25, 130, 210));
        jLabel1.setText("Giai phuong trình : ax^2+bx+c= 0");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 540, -1));

        jLabel3.setFont(new java.awt.Font("Consolas", 2, 30)); // NOI18N
        jLabel3.setText(" C");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 50, 40));

        txtC.setBackground(new java.awt.Color(231, 231, 235));
        txtC.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtC.setToolTipText("");
        txtC.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(231, 231, 235), new java.awt.Color(231, 231, 235)));
        txtC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCActionPerformed(evt);
            }
        });
        getContentPane().add(txtC, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, 110, 30));

        jLabel4.setFont(new java.awt.Font("Consolas", 2, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 0));
        jLabel4.setText("Kết quả");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, -1, 40));

        txtKq.setBackground(new java.awt.Color(231, 231, 235));
        txtKq.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtKq.setToolTipText("");
        txtKq.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(231, 231, 235), new java.awt.Color(231, 231, 235)));
        txtKq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKqActionPerformed(evt);
            }
        });
        getContentPane().add(txtKq, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 330, 40));

        jLabel6.setFont(new java.awt.Font("Consolas", 2, 30)); // NOI18N
        jLabel6.setText(" A");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 50, 40));

        txtA.setBackground(new java.awt.Color(231, 231, 235));
        txtA.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtA.setToolTipText("");
        txtA.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(231, 231, 235), new java.awt.Color(231, 231, 235)));
        txtA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAActionPerformed(evt);
            }
        });
        getContentPane().add(txtA, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 110, 30));

        jLabel7.setFont(new java.awt.Font("Consolas", 2, 30)); // NOI18N
        jLabel7.setText("B");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 50, 40));

        txtB.setBackground(new java.awt.Color(231, 231, 235));
        txtB.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtB.setToolTipText("");
        txtB.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(231, 231, 235), new java.awt.Color(231, 231, 235)));
        txtB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBActionPerformed(evt);
            }
        });
        getContentPane().add(txtB, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 110, 30));

        btnKq.setBackground(new java.awt.Color(245, 244, 189));
        btnKq.setFont(new java.awt.Font("Cambria Math", 3, 21)); // NOI18N
        btnKq.setText("Giải phương trình");
        btnKq.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(245, 244, 189), new java.awt.Color(245, 244, 189), new java.awt.Color(245, 244, 189), new java.awt.Color(245, 244, 189)));
        btnKq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKqActionPerformed(evt);
            }
        });
        getContentPane().add(btnKq, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 230, 40));

        btnResert.setBackground(new java.awt.Color(255, 204, 204));
        btnResert.setFont(new java.awt.Font("Calibri Light", 3, 18)); // NOI18N
        btnResert.setText("Reset");
        btnResert.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 204, 204), new java.awt.Color(255, 204, 204), new java.awt.Color(255, 204, 204), new java.awt.Color(255, 204, 204)));
        btnResert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResertActionPerformed(evt);
            }
        });
        getContentPane().add(btnResert, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 330, 100, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCActionPerformed

    private void txtKqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKqActionPerformed

    private void txtAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAActionPerformed

    private void txtBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBActionPerformed

    private void btnKqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKqActionPerformed
        
        String numberA = txtA.getText();
        String numberB = txtB.getText();
        String numberC = txtC.getText();    
        
         String checkNumber = "\\d{1,50}\\.\\d{1,50}";
                 
           if(numberA.isEmpty() || numberB.isEmpty() || numberC.isEmpty()){
                   JOptionPane.showMessageDialog(this, "Hãy nhập dữ liệu !","thông báo",JOptionPane.ERROR_MESSAGE);
           }else if(!numberA.matches(checkNumber) || !numberB.matches(checkNumber) || !numberC.matches(checkNumber)){
                    JOptionPane.showMessageDialog(this, "Hãy nhập số thực!","thông báo",JOptionPane.ERROR_MESSAGE);
            }else{
                    double a = Double.valueOf(numberA) ;
                    double  b = Double.valueOf(numberB) ;
                     double c = Double.valueOf(numberC) ;
                       if(a == 0){
                                 if(b == 0){
                                             if(c == 0){
                                                         JOptionPane.showMessageDialog(this, "Phương trình có vô số nghiệm !","thông báo",JOptionPane.WARNING_MESSAGE);
                                            }else{
                                                        JOptionPane.showMessageDialog(this, "Phương trình vô nghiệm !","thông báo",JOptionPane.WARNING_MESSAGE);
                                             }
                                 }else{
                                            JOptionPane.showMessageDialog(this, "Phương trình có 1 nghiệm duy nhất !","thông báo",JOptionPane.INFORMATION_MESSAGE);
                                           double  x =  - c / b;
                                           
                                            txtKq.setText("  X = "+String.valueOf(String.format("%.2f", x)));     
                                 }
                        }else{
                                   double delta = Math.pow(b, 2) - 4*a*c;
                                   if(delta > 0){
                                            double x1 = (-b + Math.sqrt(delta))/(2*a);
                                            double x2 = (-b - Math.sqrt(delta))/(2*a);

                                             JOptionPane.showMessageDialog(this, "Phương trình có 2 nghiệm phân biệt!","thông báo",JOptionPane.INFORMATION_MESSAGE);
                                             txtKq.setText("  X1 = "+String.valueOf(String.format("%.2f", x1))+" \t X2 = "+String.valueOf(String.format("%.2f", x2)));                                    
                                   }else if(delta ==0){
                                            double x = -b/2*a;
                                 
                                            JOptionPane.showMessageDialog(this, "Phương trình có nghiệm kép!","thông báo",JOptionPane.INFORMATION_MESSAGE);
                                              
                                             txtKq.setText("  X1 = "+String.valueOf(String.format("%.2f", x)));                 
                                   }else{
                                              JOptionPane.showMessageDialog(this, "Phương trình vô nghiệm !","thông báo",JOptionPane.WARNING_MESSAGE);
                                   }

                        }
                    
               
           }

    }//GEN-LAST:event_btnKqActionPerformed

    private void btnResertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResertActionPerformed
        txtA.setText("");
        txtB.setText("");
        txtC.setText("");
        txtKq.setText("");
    }//GEN-LAST:event_btnResertActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lesson4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lesson4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lesson4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lesson4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lesson4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKq;
    private javax.swing.JButton btnResert;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtA;
    private javax.swing.JTextField txtB;
    private javax.swing.JTextField txtC;
    private javax.swing.JTextField txtKq;
    // End of variables declaration//GEN-END:variables
}
