/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bailamthemLab2.javaSwing;

import javax.swing.JOptionPane;

/**
 *
 * @author HL COMPUTER
 */
public class lesson5 extends javax.swing.JFrame {

    /**
     * Creates new form lesson5
     */
    public lesson5() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtA = new javax.swing.JTextField();
        btnKq = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtKq = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtB = new javax.swing.JTextField();
        cboSign = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        btnResert = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(760, 470));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe Script", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(25, 130, 210));
        jLabel1.setText("Tính toán");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Consolas", 2, 30)); // NOI18N
        jLabel3.setText("A");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 40, 40));

        txtA.setBackground(new java.awt.Color(231, 231, 235));
        txtA.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtA.setToolTipText("");
        txtA.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(231, 231, 235), new java.awt.Color(231, 231, 235)));
        txtA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAActionPerformed(evt);
            }
        });
        getContentPane().add(txtA, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 160, 30));

        btnKq.setBackground(new java.awt.Color(255, 204, 204));
        btnKq.setFont(new java.awt.Font("Calibri Light", 3, 23)); // NOI18N
        btnKq.setText("Thực hiện");
        btnKq.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 204, 204), new java.awt.Color(255, 204, 204), new java.awt.Color(255, 204, 204), new java.awt.Color(255, 204, 204)));
        btnKq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKqActionPerformed(evt);
            }
        });
        getContentPane().add(btnKq, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 150, 40));

        jLabel4.setFont(new java.awt.Font("Consolas", 2, 25)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 102));
        jLabel4.setText("Kết quả");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, -1, 40));

        txtKq.setBackground(new java.awt.Color(231, 231, 235));
        txtKq.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtKq.setToolTipText("");
        txtKq.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(231, 231, 235), new java.awt.Color(231, 231, 235)));
        txtKq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKqActionPerformed(evt);
            }
        });
        getContentPane().add(txtKq, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, 160, 30));

        jLabel5.setFont(new java.awt.Font("Consolas", 2, 30)); // NOI18N
        jLabel5.setText("B");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 40, 40));

        txtB.setBackground(new java.awt.Color(231, 231, 235));
        txtB.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtB.setToolTipText("");
        txtB.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(231, 231, 235), new java.awt.Color(231, 231, 235)));
        txtB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBActionPerformed(evt);
            }
        });
        getContentPane().add(txtB, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, 160, 30));

        cboSign.setFont(new java.awt.Font("Consolas", 3, 14)); // NOI18N
        cboSign.setForeground(new java.awt.Color(51, 51, 51));
        cboSign.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "+", "-", "*", "/" }));
        cboSign.setToolTipText("");
        cboSign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboSignActionPerformed(evt);
            }
        });
        getContentPane().add(cboSign, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 50, 30));

        jLabel6.setFont(new java.awt.Font("Consolas", 2, 25)); // NOI18N
        jLabel6.setText("Phép tính");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, 40));

        btnResert.setBackground(new java.awt.Color(255, 204, 204));
        btnResert.setFont(new java.awt.Font("Calibri Light", 3, 18)); // NOI18N
        btnResert.setText("Reset");
        btnResert.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 204, 204), new java.awt.Color(255, 204, 204), new java.awt.Color(255, 204, 204), new java.awt.Color(255, 204, 204)));
        btnResert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResertActionPerformed(evt);
            }
        });
        getContentPane().add(btnResert, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, 100, 40));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAActionPerformed

    private void btnKqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKqActionPerformed
          if (txtA.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Hãy nhập số a !", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (txtB.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Hãy nhập số b  !", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
            
        double a = Double.parseDouble(txtA.getText());
        double b = Double.parseDouble(txtB.getText());
        
        switch(cboSign.getSelectedIndex()){
            case 0: txtKq.setText(String.valueOf(a + b)); break;
            case 1: txtKq.setText(String.valueOf(a - b)); break;
            case 2: txtKq.setText(String.valueOf(a * b)); break;
            case 3: txtKq.setText(String.valueOf(a / b)); break;
        }
        
        
    }//GEN-LAST:event_btnKqActionPerformed

    private void txtKqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKqActionPerformed

    private void txtBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBActionPerformed

    private void cboSignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboSignActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboSignActionPerformed

    private void btnResertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResertActionPerformed
        txtA.setText("");
        txtB.setText("");
        txtKq.setText("");
    }//GEN-LAST:event_btnResertActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lesson5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lesson5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lesson5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lesson5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lesson5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKq;
    private javax.swing.JButton btnResert;
    private javax.swing.JComboBox<String> cboSign;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtA;
    private javax.swing.JTextField txtB;
    private javax.swing.JTextField txtKq;
    // End of variables declaration//GEN-END:variables
}
