/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package bailamthemLab2.javaSwing;

import javax.swing.JOptionPane;

/**
 *
 * @author HL COMPUTER
 */
public class lesson2 extends javax.swing.JFrame {

    /** Creates new form lesson2 */
    public lesson2() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtC = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtA = new javax.swing.JTextField();
        txtB = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtKq3 = new javax.swing.JTextField();
        txtKq2 = new javax.swing.JTextField();
        txtKq1 = new javax.swing.JTextField();
        btn1 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(950, 640));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtC.setBackground(new java.awt.Color(231, 231, 235));
        txtC.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtC.setToolTipText("");
        txtC.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(231, 231, 235), new java.awt.Color(231, 231, 235)));
        txtC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCActionPerformed(evt);
            }
        });
        jPanel1.add(txtC, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 170, 30));

        jLabel6.setFont(new java.awt.Font("Consolas", 2, 25)); // NOI18N
        jLabel6.setText("Số B");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 80, 40));

        txtA.setBackground(new java.awt.Color(231, 231, 235));
        txtA.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtA.setToolTipText("");
        txtA.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(231, 231, 235), new java.awt.Color(231, 231, 235)));
        txtA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAActionPerformed(evt);
            }
        });
        jPanel1.add(txtA, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 170, 30));

        txtB.setBackground(new java.awt.Color(231, 231, 235));
        txtB.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtB.setToolTipText("");
        txtB.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(231, 231, 235), new java.awt.Color(231, 231, 235)));
        txtB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBActionPerformed(evt);
            }
        });
        jPanel1.add(txtB, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 170, 30));

        jLabel7.setFont(new java.awt.Font("Consolas", 2, 25)); // NOI18N
        jLabel7.setText("Số C");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 80, 40));

        jLabel8.setFont(new java.awt.Font("Consolas", 2, 25)); // NOI18N
        jLabel8.setText("Số A");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 80, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 280, 250));

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtKq3.setBackground(new java.awt.Color(231, 231, 235));
        txtKq3.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtKq3.setToolTipText("");
        txtKq3.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(231, 231, 235), new java.awt.Color(231, 231, 235)));
        txtKq3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKq3ActionPerformed(evt);
            }
        });
        jPanel2.add(txtKq3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 230, 30));

        txtKq2.setBackground(new java.awt.Color(231, 231, 235));
        txtKq2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtKq2.setToolTipText("");
        txtKq2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(231, 231, 235), new java.awt.Color(231, 231, 235)));
        txtKq2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKq2ActionPerformed(evt);
            }
        });
        jPanel2.add(txtKq2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 230, 30));

        txtKq1.setBackground(new java.awt.Color(231, 231, 235));
        txtKq1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtKq1.setToolTipText("");
        txtKq1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(231, 231, 235), new java.awt.Color(231, 231, 235)));
        txtKq1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKq1ActionPerformed(evt);
            }
        });
        jPanel2.add(txtKq1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 230, 30));

        btn1.setBackground(new java.awt.Color(204, 204, 204));
        btn1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn1.setText("A + B + C");
        btn1.setActionCommand("A + B - C");
        btn1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jPanel2.add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 100, 30));

        btn3.setBackground(new java.awt.Color(204, 204, 204));
        btn3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn3.setText("A - B +C");
        btn3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        jPanel2.add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 100, 30));

        btn2.setBackground(new java.awt.Color(204, 204, 204));
        btn2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn2.setText("A + B - C");
        btn2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        jPanel2.add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 100, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, 410, 250));

        jLabel1.setFont(new java.awt.Font("Segoe Script", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(25, 130, 210));
        jLabel1.setText("Làm toán");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel4.setText("Kết quả");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, -1, 40));

        jLabel5.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel5.setText("Nhập dữ liệu");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, 40));

        btnReset.setBackground(new java.awt.Color(204, 204, 204));
        btnReset.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        btnReset.setText("Tiếp tục");
        btnReset.setToolTipText("");
        btnReset.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        getContentPane().add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 480, 160, 50));

        btnExit.setBackground(new java.awt.Color(204, 204, 204));
        btnExit.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        btnExit.setText("Thoát");
        btnExit.setToolTipText("");
        btnExit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 480, 160, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCActionPerformed

    private void txtAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAActionPerformed

    private void txtBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBActionPerformed

    private void txtKq3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKq3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKq3ActionPerformed

    private void txtKq2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKq2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKq2ActionPerformed

    private void txtKq1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKq1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKq1ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        String numberA = txtA.getText();
        String numberB = txtB.getText();
        String numberC = txtC.getText();
        
         String checkNumber = "\\d{1,50}\\.\\d{1,50}";
                 
           if(numberA.isEmpty() || numberB.isEmpty() || numberC.isEmpty()){
                   JOptionPane.showMessageDialog(this, "Hãy nhập dữ liệu !","thông báo",JOptionPane.ERROR_MESSAGE);
           }else if(!numberA.matches(checkNumber) || !numberB.matches(checkNumber) || !numberC.matches(checkNumber)){
                    JOptionPane.showMessageDialog(this, "Hãy nhập số thực!","thông báo",JOptionPane.ERROR_MESSAGE);
            }else{
                     double a = Double.valueOf(numberA) ;
                    double  b = Double.valueOf(numberB) ;
                    double c = Double.valueOf(numberC) ;
                    
                    double kq = a + b + c;
                    txtKq1.setText(String.valueOf(String.format("%.2f", kq)));
               
           }
    }//GEN-LAST:event_btn1ActionPerformed
                      
    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
         String numberA = txtA.getText();
        String numberB = txtB.getText();
        String numberC = txtC.getText();
        
         String checkNumber = "\\d{1,50}\\.\\d{1,50}";
                 
           if(numberA.isEmpty() || numberB.isEmpty() || numberC.isEmpty()){
                   JOptionPane.showMessageDialog(this, "Hãy nhập dữ liệu !","thông báo",JOptionPane.ERROR_MESSAGE);
           }else if(!numberA.matches(checkNumber) || !numberB.matches(checkNumber) || !numberC.matches(checkNumber)){
                    JOptionPane.showMessageDialog(this, "Hãy nhập số thực!","thông báo",JOptionPane.ERROR_MESSAGE);
            }else{
                     double a = Double.valueOf(numberA) ;
                    double  b = Double.valueOf(numberB) ;
                    double c = Double.valueOf(numberC) ;
                    
                    double kq = a - b + c;
                    txtKq3.setText(String.valueOf(String.format("%.2f", kq)));
               
           }
    }//GEN-LAST:event_btn3ActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
       txtA.setText("");
        txtB.setText("");
        txtC.setText("");
        txtKq1.setText("");
        txtKq2.setText("");
        txtKq3.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
       System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
                String numberA = txtA.getText();
        String numberB = txtB.getText();
        String numberC = txtC.getText();
        
         String checkNumber = "\\d{1,50}\\.\\d{1,50}";
                 
           if(numberA.isEmpty() || numberB.isEmpty() || numberC.isEmpty()){
                   JOptionPane.showMessageDialog(this, "Hãy nhập dữ liệu !","thông báo",JOptionPane.ERROR_MESSAGE);
           }else if(!numberA.matches(checkNumber) || !numberB.matches(checkNumber) || !numberC.matches(checkNumber)){
                    JOptionPane.showMessageDialog(this, "Hãy nhập số thực!","thông báo",JOptionPane.ERROR_MESSAGE);
            }else{
                     double a = Double.valueOf(numberA) ;
                    double  b = Double.valueOf(numberB) ;
                    double c = Double.valueOf(numberC) ;
                    
                    double kq = a + b - c;
                    txtKq2.setText(String.valueOf(String.format("%.2f", kq)));
               
           }
    }//GEN-LAST:event_btn2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lesson2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lesson2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lesson2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lesson2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lesson2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnReset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtA;
    private javax.swing.JTextField txtB;
    private javax.swing.JTextField txtC;
    private javax.swing.JTextField txtKq1;
    private javax.swing.JTextField txtKq2;
    private javax.swing.JTextField txtKq3;
    // End of variables declaration//GEN-END:variables

}
