/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ph26495.com1023.lesson4;

/**
 *
 * @author HL COMPUTER
 */
public class Sskt extends javax.swing.JFrame {

    
 
    /**
     * Creates new form Sskt
     */
    public Sskt() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTram = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblChuc = new javax.swing.JLabel();
        lblDonvi = new javax.swing.JPanel();
        lblDv = new javax.swing.JLabel();
        BtnStartDv = new javax.swing.JButton();
        btnStartTram = new javax.swing.JButton();
        btnRset = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnStartChuc = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Trăm", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 18), new java.awt.Color(255, 0, 0))); // NOI18N

        lblTram.setFont(new java.awt.Font("Segoe UI Semilight", 1, 20)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblTram, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblTram, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 110, 90));

        jLabel10.setFont(new java.awt.Font("Colonna MT", 3, 40)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(84, 178, 224));
        jLabel10.setText("SO SO KIEN THIET");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 440, 50));

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Chục", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 18), new java.awt.Color(255, 0, 0))); // NOI18N

        lblChuc.setFont(new java.awt.Font("Segoe UI Semilight", 1, 20)); // NOI18N
        lblChuc.setText("       ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblChuc)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblChuc)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 110, 90));

        lblDonvi.setBackground(new java.awt.Color(255, 255, 153));
        lblDonvi.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Đơn vị", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 18), new java.awt.Color(255, 0, 0))); // NOI18N

        lblDv.setFont(new java.awt.Font("Segoe UI Semilight", 1, 20)); // NOI18N
        lblDv.setText("       ");

        javax.swing.GroupLayout lblDonviLayout = new javax.swing.GroupLayout(lblDonvi);
        lblDonvi.setLayout(lblDonviLayout);
        lblDonviLayout.setHorizontalGroup(
            lblDonviLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblDonviLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblDv)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        lblDonviLayout.setVerticalGroup(
            lblDonviLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblDonviLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDv)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        getContentPane().add(lblDonvi, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 110, 90));

        BtnStartDv.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        BtnStartDv.setText("Start");
        BtnStartDv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnStartDvActionPerformed(evt);
            }
        });
        getContentPane().add(BtnStartDv, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 80, 40));

        btnStartTram.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnStartTram.setText("Start");
        btnStartTram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartTramActionPerformed(evt);
            }
        });
        getContentPane().add(btnStartTram, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 80, 40));

        btnRset.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnRset.setText("Refresh");
        btnRset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRsetActionPerformed(evt);
            }
        });
        getContentPane().add(btnRset, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 110, 40));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 253, 330, 20));

        btnStartChuc.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnStartChuc.setText("Start");
        btnStartChuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartChucActionPerformed(evt);
            }
        });
        getContentPane().add(btnStartChuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 70, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartTramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartTramActionPerformed
     new Thread() {
            @Override
            public void run() {
                   for(int i = 0; i <= 1000;i++){
                       try {
                           int numberRandom = (int) Math.round(Math.random()*9);
                           lblTram.setText(String.valueOf(numberRandom));
                           Thread.sleep(10);  
                       } catch (Exception e) {
                           e.printStackTrace();
                           break;
                       } 
                       
                   }
            }
        }.start();
        //vô hiệu hóa nút 
        btnStartTram.setEnabled(false);
        
        
    }//GEN-LAST:event_btnStartTramActionPerformed

    private void btnStartChucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartChucActionPerformed
       new Thread() {
            @Override
            public void run() {
                   for(int i = 0; i <= 1000;i++){
                       try {
                           int numberRandom = (int) Math.round(Math.random()*9);
                           lblChuc.setText(String.valueOf(numberRandom));
                           Thread.sleep(10);  
                       } catch (Exception e) {
                           e.printStackTrace();
                           break;
                       } 
                       
                   }
            }
        }.start();
        //vô hiệu hóa nút 
        btnStartChuc.setEnabled(false);
    }//GEN-LAST:event_btnStartChucActionPerformed

    private void BtnStartDvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnStartDvActionPerformed
        new Thread() {
            @Override
            public void run() {
                   for(int i = 0; i <= 1000;i++){
                       try {
                           int numberRandom = (int) Math.round(Math.random()*9);
                           lblDv.setText(String.valueOf(numberRandom));
                           Thread.sleep(10);  
                       } catch (Exception e) {
                           e.printStackTrace();
                           break;
                       } 
                       
                   }
            }
        }.start();
        //vô hiệu hóa nút 
        BtnStartDv.setEnabled(false);
    }//GEN-LAST:event_BtnStartDvActionPerformed

    private void btnRsetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRsetActionPerformed
       btnStartChuc.setEnabled(true);
       btnStartTram.setEnabled(true);
       BtnStartDv.setEnabled(true);
       lblChuc.setText("");
       lblDv.setText("");
       lblTram.setText("");
   
       
    }//GEN-LAST:event_btnRsetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sskt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sskt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sskt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sskt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sskt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnStartDv;
    private javax.swing.JButton btnRset;
    private javax.swing.JButton btnStartChuc;
    private javax.swing.JButton btnStartTram;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblChuc;
    private javax.swing.JPanel lblDonvi;
    private javax.swing.JLabel lblDv;
    private javax.swing.JLabel lblTram;
    // End of variables declaration//GEN-END:variables
}
