/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BaiLamThemLab4;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HL COMPUTER
 */
public class qlGv extends javax.swing.JFrame {

    /**
     * Creates new form qlGv
     */
    List<Info_Teacher> listTeachers = new ArrayList<>();
    int index;  //Biến toàn cục

    public qlGv() {
        initComponents();
         listTeachers.add(new Info_Teacher("H1", "Le văn a", "LTMT"));         //add cứng vào table 
        listTeachers.add(new Info_Teacher("H2", "Le văn b", "TMDT"));
        findToTable();
        showData(0);  //Luôn hiện dòng đầu khi chạy       listTeachers.add(new Info_Teacher("H1", "Le văn a", "LTMT"));         //add cứng vào table 
        listTeachers.add(new Info_Teacher("H2", "Le văn b", "TMDT"));
        findToTable();
        showData(0);  //Luôn hiện dòng đầu khi chạy
    }

    //Hàm thêm
    public void insert() {
        Info_Teacher teacher = new Info_Teacher();
        teacher.setId(txtID.getText());
        teacher.setName(txtName.getText());
        teacher.setFaculity((String) cboFaculity.getSelectedItem());

        listTeachers.add(teacher);

    }
    //Hàm đổ dữ liệu vào bảng

    public void findToTable() {
        DefaultTableModel model = (DefaultTableModel) tblDsTeacher.getModel();
        model.setRowCount(0);
        for (Info_Teacher ds : listTeachers) {
            Object[] row = new Object[]{
                ds.getId(), ds.getName(), ds.getFaculity()
            };
            model.addRow(row);
        }

    }

    //Hiện dữ liệu lên text view
    public void showData(int index) {
        txtID.setText((String) tblDsTeacher.getValueAt(index, 0));
        txtName.setText((String) tblDsTeacher.getValueAt(index, 1));
        cboFaculity.setSelectedItem(tblDsTeacher.getValueAt(index, 2));
        lblOder.setText((index + 1) + "/" + listTeachers.size());
        
        tblDsTeacher.setRowSelectionInterval(index, index); //Xét dòng con trỏ trong bảng 
    }

    //Hàm reset 
    public void reset() {
        txtID.setText("");
        txtName.setText("");
        cboFaculity.setSelectedIndex(0);
    }

    //Nút delete
    public void delete() {
        index = tblDsTeacher.getSelectedRow();
        int choice = (JOptionPane.showConfirmDialog(this, "Xóa thông tin người dùng?", "Confirm", JOptionPane.YES_NO_OPTION));
        if (choice == JOptionPane.YES_OPTION) {
            listTeachers.remove(index);
            findToTable();
            JOptionPane.showMessageDialog(this, "Đã xóa người dùng trong list!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        } else {
            return;
        }
    }

    //Nút update
    public void update() {
        index = tblDsTeacher.getSelectedRow();
        Info_Teacher sv = listTeachers.get(index);
        sv.setId(txtID.getText());
        sv.setName(txtName.getText());
        sv.setFaculity((String) cboFaculity.getSelectedItem());

        int choice = (JOptionPane.showConfirmDialog(this, "Cập nhật thông tin người dùng này?", "Confirm", JOptionPane.YES_NO_OPTION));
        if (choice == JOptionPane.YES_OPTION) {
            findToTable();
            JOptionPane.showMessageDialog(this, "Đã cập nhật người dùng trong list!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        } else {
            return;
        }
    }

    //Nút về đầu 
    public void first() {
        index = 0;
        showData(index);
    }

    //Nút về cuối 
    public void last() {
        index = listTeachers.size() - 1;
        showData(index);
    }
    //Nút lùi xuống

    public void BackBottom() {
        if (index > 0) {
            index--;
            showData(index);
        }
    }

    //Nút tiến lên
    public void BackTop() {
        if (index < listTeachers.size() - 1) {
            index++;
            showData(index);
        }
    }

    //
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        lblOder = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cboFaculity = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDsTeacher = new javax.swing.JTable();
        btnRefresh = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnInsert = new javax.swing.JButton();
        btnBackBottom = new javax.swing.JButton();
        btnBackToLast = new javax.swing.JButton();
        btnBackToFirst = new javax.swing.JButton();
        btnBackTop = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 650));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Colonna MT", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 204));
        jLabel8.setText("Teacher Management");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 380, 60));

        lblOder.setFont(new java.awt.Font("Consolas", 2, 20)); // NOI18N
        getContentPane().add(lblOder, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 60, 40));

        txtID.setBackground(new java.awt.Color(231, 231, 235));
        txtID.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtID.setToolTipText("");
        txtID.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(231, 231, 235), new java.awt.Color(231, 231, 235)));
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        getContentPane().add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 360, 30));

        txtName.setBackground(new java.awt.Color(231, 231, 235));
        txtName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtName.setToolTipText("");
        txtName.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(231, 231, 235), new java.awt.Color(231, 231, 235)));
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 360, 30));

        jLabel4.setFont(new java.awt.Font("Consolas", 2, 18)); // NOI18N
        jLabel4.setText("Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, 40));

        cboFaculity.setFont(new java.awt.Font("Consolas", 3, 19)); // NOI18N
        cboFaculity.setForeground(new java.awt.Color(51, 51, 51));
        cboFaculity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LTMT", "TMDT", "LTMOB", "TKWEB" }));
        cboFaculity.setToolTipText("");
        cboFaculity.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                cboFaculityComponentHidden(evt);
            }
        });
        cboFaculity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboFaculityActionPerformed(evt);
            }
        });
        getContentPane().add(cboFaculity, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 170, 40));

        jLabel6.setFont(new java.awt.Font("Consolas", 2, 18)); // NOI18N
        jLabel6.setText("Faculity");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, 40));

        tblDsTeacher.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NAME", "FACULITY"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblDsTeacher.setToolTipText("");
        tblDsTeacher.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblDsTeacher.setDoubleBuffered(true);
        tblDsTeacher.setFillsViewportHeight(true);
        tblDsTeacher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDsTeacherMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDsTeacher);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 660, 220));

        btnRefresh.setBackground(new java.awt.Color(255, 204, 204));
        btnRefresh.setFont(new java.awt.Font("Calibri Light", 3, 18)); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.setToolTipText("");
        btnRefresh.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 204, 204), new java.awt.Color(255, 204, 204), new java.awt.Color(255, 204, 204), new java.awt.Color(255, 204, 204)));
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        getContentPane().add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 270, 120, 30));

        btnUpdate.setBackground(new java.awt.Color(255, 204, 204));
        btnUpdate.setFont(new java.awt.Font("Calibri Light", 3, 18)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.setToolTipText("");
        btnUpdate.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 204, 204), new java.awt.Color(255, 204, 204), new java.awt.Color(255, 204, 204), new java.awt.Color(255, 204, 204)));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 170, 120, 30));

        btnDelete.setBackground(new java.awt.Color(255, 204, 204));
        btnDelete.setFont(new java.awt.Font("Calibri Light", 3, 18)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.setToolTipText("");
        btnDelete.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 204, 204), new java.awt.Color(255, 204, 204), new java.awt.Color(255, 204, 204), new java.awt.Color(255, 204, 204)));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 220, 120, 30));

        btnInsert.setBackground(new java.awt.Color(255, 204, 204));
        btnInsert.setFont(new java.awt.Font("Calibri Light", 3, 18)); // NOI18N
        btnInsert.setText("Insert");
        btnInsert.setToolTipText("");
        btnInsert.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 204, 204), new java.awt.Color(255, 204, 204), new java.awt.Color(255, 204, 204), new java.awt.Color(255, 204, 204)));
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });
        getContentPane().add(btnInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 120, 120, 30));

        btnBackBottom.setBackground(new java.awt.Color(160, 229, 227));
        btnBackBottom.setFont(new java.awt.Font("Calibri Light", 3, 18)); // NOI18N
        btnBackBottom.setText("<<");
        btnBackBottom.setToolTipText("");
        btnBackBottom.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(160, 229, 227), new java.awt.Color(160, 229, 227), new java.awt.Color(160, 229, 227), new java.awt.Color(160, 229, 227)));
        btnBackBottom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackBottomActionPerformed(evt);
            }
        });
        getContentPane().add(btnBackBottom, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 60, 30));

        btnBackToLast.setBackground(new java.awt.Color(160, 229, 227));
        btnBackToLast.setFont(new java.awt.Font("Calibri Light", 3, 18)); // NOI18N
        btnBackToLast.setText(">|");
        btnBackToLast.setToolTipText("");
        btnBackToLast.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(160, 229, 227), new java.awt.Color(160, 229, 227), new java.awt.Color(160, 229, 227), new java.awt.Color(160, 229, 227)));
        btnBackToLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToLastActionPerformed(evt);
            }
        });
        getContentPane().add(btnBackToLast, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 320, 60, 30));

        btnBackToFirst.setBackground(new java.awt.Color(160, 229, 227));
        btnBackToFirst.setFont(new java.awt.Font("Calibri Light", 3, 18)); // NOI18N
        btnBackToFirst.setText("|<");
        btnBackToFirst.setToolTipText("");
        btnBackToFirst.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(160, 229, 227), new java.awt.Color(160, 229, 227), new java.awt.Color(160, 229, 227), new java.awt.Color(160, 229, 227)));
        btnBackToFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToFirstActionPerformed(evt);
            }
        });
        getContentPane().add(btnBackToFirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 60, 30));

        btnBackTop.setBackground(new java.awt.Color(160, 229, 227));
        btnBackTop.setFont(new java.awt.Font("Calibri Light", 3, 18)); // NOI18N
        btnBackTop.setText(">>");
        btnBackTop.setToolTipText("");
        btnBackTop.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(160, 229, 227), new java.awt.Color(160, 229, 227), new java.awt.Color(160, 229, 227), new java.awt.Color(160, 229, 227)));
        btnBackTop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackTopActionPerformed(evt);
            }
        });
        getContentPane().add(btnBackTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, 60, 30));

        jLabel2.setFont(new java.awt.Font("Consolas", 2, 18)); // NOI18N
        jLabel2.setText("ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 100, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed

    }//GEN-LAST:event_txtIDActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void cboFaculityComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_cboFaculityComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_cboFaculityComponentHidden

    private void cboFaculityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboFaculityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboFaculityActionPerformed

    private void tblDsTeacherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDsTeacherMouseClicked
        index = tblDsTeacher.getSelectedRow();
        showData(index);
    }//GEN-LAST:event_tblDsTeacherMouseClicked

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        reset();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        update();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        delete();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        insert();
        findToTable();
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnBackBottomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackBottomActionPerformed
        BackBottom();
    }//GEN-LAST:event_btnBackBottomActionPerformed

    private void btnBackToLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToLastActionPerformed
        last();
    }//GEN-LAST:event_btnBackToLastActionPerformed

    private void btnBackToFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToFirstActionPerformed
        first();
    }//GEN-LAST:event_btnBackToFirstActionPerformed

    private void btnBackTopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackTopActionPerformed
        BackTop();
    }//GEN-LAST:event_btnBackTopActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(qlGv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(qlGv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(qlGv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(qlGv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new qlGv().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackBottom;
    private javax.swing.JButton btnBackToFirst;
    private javax.swing.JButton btnBackToLast;
    private javax.swing.JButton btnBackTop;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cboFaculity;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblOder;
    private javax.swing.JTable tblDsTeacher;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
