/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lesson2;

import java.awt.Dialog;
import javax.swing.JOptionPane;

/**
 *
 * @author HL COMPUTER
 */
public class lab7Bai2Jfram extends javax.swing.JFrame {

    /**
     * Creates new form lab7Bai2Jfram
     */
    public lab7Bai2Jfram() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtSum = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtString2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtString1 = new javax.swing.JTextField();
        btnKq = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 250));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Colonna MT", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 204));
        jLabel8.setText(" Lesson2");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 160, 60));

        jLabel1.setFont(new java.awt.Font("Consolas", 3, 18)); // NOI18N
        jLabel1.setText("Chuỗi 1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 92, -1, 30));

        txtSum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSumActionPerformed(evt);
            }
        });
        getContentPane().add(txtSum, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 130, 30));

        jLabel2.setFont(new java.awt.Font("Consolas", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("Tổng ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 60, 50));

        txtString2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtString2ActionPerformed(evt);
            }
        });
        getContentPane().add(txtString2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 100, 30));

        jLabel3.setFont(new java.awt.Font("Consolas", 3, 18)); // NOI18N
        jLabel3.setText("Chuỗi 2");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 92, -1, 30));

        txtString1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtString1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtString1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 100, 30));

        btnKq.setText("Kết quả");
        btnKq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKqActionPerformed(evt);
            }
        });
        getContentPane().add(btnKq, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 90, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSumActionPerformed

    private void txtString2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtString2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtString2ActionPerformed

    private void txtString1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtString1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtString1ActionPerformed

    private void btnKqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKqActionPerformed
        String string1 = txtString1.getText().toString();
        String string2 = txtString2.getText().toString();
        try {
            double number1 = Double.parseDouble(string1);
            double number2 = Double.parseDouble(string2);
            double sum = number1 + number2;
            txtSum.setText(String.valueOf(sum));
            JOptionPane.showMessageDialog(this, "Chuyển đổi thành công");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Không chuyển đổi được chuỗi");
        }
    }//GEN-LAST:event_btnKqActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lab7Bai2Jfram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lab7Bai2Jfram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lab7Bai2Jfram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lab7Bai2Jfram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lab7Bai2Jfram().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKq;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtString1;
    private javax.swing.JTextField txtString2;
    private javax.swing.JTextField txtSum;
    // End of variables declaration//GEN-END:variables
}
