/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ph26495_ktlab7;

import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HL COMPUTER
 */
public class Qlgv extends javax.swing.JFrame {

    ArrayList<GiaoVien> listGv = new ArrayList<>();
    int index;

    /**
     * Creates new form Qlgv
     */
    public Qlgv() {
        initComponents();
        listGv.add(new GiaoVien("le van a", 4, "Nam"));
        listGv.add(new GiaoVien("le van b", 7, "Nữ"));
        listGv.add(new GiaoVien("le van c", 9, "Nữ"));
        findToTable();
        showData(0);

    }

    public void insert() {

        try {
            if (txtName.getText().equals("") || txtDiem.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Không được để trống!");
            } else if (Double.parseDouble(txtDiem.getText()) < 0 || Double.parseDouble(txtDiem.getText()) > 10) {
                JOptionPane.showMessageDialog(this, "Nhập điểm từ 0 đến 10!");
            } else if (!rdoNam.isSelected() && !rdoNu.isSelected()) {

                JOptionPane.showMessageDialog(this, "Hãy chọn giới tính!");
            } else {
                GiaoVien gv = new GiaoVien();
                gv.setTen(txtName.getText().toString());
                gv.setDiem(Double.parseDouble(txtDiem.getText()));
                gv.setGioitinh(rdoNam.isSelected() ? "Nam" : "Nữ");

                listGv.add(gv);
                findToTable();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Nhập điểm là số");
        }

    }

    public void findToTable() {
        DefaultTableModel model = (DefaultTableModel) lblListGv.getModel();
        model.setRowCount(0);
        for (GiaoVien gv : listGv) {
            Object[] row = new Object[]{
                gv.getTen(), gv.getDiem(), gv.getGioitinh(), gv.xepLoai(gv.getDiem())
            };
            model.addRow(row);
        }

    }

    public void showData(int index) {
        txtName.setText((String) lblListGv.getValueAt(index, 0));
        txtDiem.setText(lblListGv.getValueAt(index, 1) + "");
        if (lblListGv.getValueAt(index, 2).equals("Nam")) {
            rdoNam.setSelected(true);
            rdoNu.setSelected(false);
        } else {
            rdoNam.setSelected(false);
            rdoNu.setSelected(true);
        }
        lblListGv.setRowSelectionInterval(index, index);

    }

    public void delete(int index) {
        index = lblListGv.getSelectedRow();
        listGv.remove(index);
        findToTable();

    }

    public void update(int index) {
        try {
            if (txtName.getText().equals("") || txtDiem.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Không được để trống!");
            } else if (Double.parseDouble(txtDiem.getText()) < 0 || Double.parseDouble(txtDiem.getText()) > 10) {
                JOptionPane.showMessageDialog(this, "Nhập điểm từ 0 đến 10!");
            } else {
                GiaoVien gv = listGv.get(index);
                gv.setTen(txtName.getText().toString());
                gv.setDiem(Double.parseDouble(txtDiem.getText()));
                if (rdoNam.isSelected()) {
                    gv.setGioitinh("Nam");
                } else {
                    gv.setGioitinh("Nữ");
                }
                findToTable();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Nhập điểm là số");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rdoGr = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDiem = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lblListGv = new javax.swing.JTable();
        btnUpdate = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnOpen = new javax.swing.JButton();
        btnInsert = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        rdoNam = new javax.swing.JRadioButton();
        rdoNu = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Quản lí giáo viên");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 220, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 16)); // NOI18N
        jLabel2.setText("Họ tên");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, 30));
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 200, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 2, 16)); // NOI18N
        jLabel3.setText("Giới tính");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, 30));
        getContentPane().add(txtDiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 200, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 2, 16)); // NOI18N
        jLabel4.setText("Điểm");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, 30));

        lblListGv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Họ tên", "Điểm", "Giới tính", "Xếp loại"
            }
        ));
        lblListGv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblListGvMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lblListGv);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 490, 170));

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, -1, -1));

        btnSave.setText("SaveFile");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, -1, -1));

        btnOpen.setText("Open");
        btnOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenActionPerformed(evt);
            }
        });
        getContentPane().add(btnOpen, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, -1, -1));

        btnInsert.setText("Insert");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });
        getContentPane().add(btnInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, -1, -1));

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, -1, -1));

        rdoGr.add(rdoNam);
        rdoNam.setText("Nam");
        rdoNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoNamActionPerformed(evt);
            }
        });
        getContentPane().add(rdoNam, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, -1, -1));

        rdoGr.add(rdoNu);
        rdoNu.setText("Nữ");
        getContentPane().add(rdoNu, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdoNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoNamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoNamActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try {
            ObjectOutputStream oos = new ObjectOutputStream(new FileOutputStream("lab7.txt"));
            oos.writeObject(listGv);
            oos.flush();
            oos.close();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenActionPerformed
        try {
            ObjectInputStream ois = new ObjectInputStream(new FileInputStream("lab7.txt"));
            listGv = (ArrayList<GiaoVien>) ois.readObject();
            findToTable();
            ois.close();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnOpenActionPerformed

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        insert();
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        delete(index);
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        update(index);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void lblListGvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblListGvMouseClicked
        index = lblListGv.getSelectedRow();
        showData(index);
    }//GEN-LAST:event_lblListGvMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Qlgv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Qlgv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Qlgv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Qlgv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Qlgv().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnOpen;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable lblListGv;
    private javax.swing.ButtonGroup rdoGr;
    private javax.swing.JRadioButton rdoNam;
    private javax.swing.JRadioButton rdoNu;
    private javax.swing.JTextField txtDiem;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
