/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lesson3;

import javax.swing.JOptionPane;

/**
 *
 * @author HL COMPUTER
 */
public class lab7Bai3Jfram extends javax.swing.JFrame {

    /**
     * Creates new form lab7Bai3Jfram
     */
    public lab7Bai3Jfram() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtA = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtB = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtSqrt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtExponential = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtMin = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtMax = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnKq = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Colonna MT", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 204));
        jLabel8.setText(" Lesson3");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 160, 60));

        jLabel1.setFont(new java.awt.Font("Consolas", 3, 18)); // NOI18N
        jLabel1.setText("Credit Card :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 140, 30));

        txtA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAActionPerformed(evt);
            }
        });
        getContentPane().add(txtA, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 290, 30));

        jLabel2.setFont(new java.awt.Font("Consolas", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("Kết quả");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, 30));

        txtB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBActionPerformed(evt);
            }
        });
        getContentPane().add(txtB, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 290, 30));

        jLabel3.setFont(new java.awt.Font("Consolas", 3, 18)); // NOI18N
        jLabel3.setText("Số thứ 2:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, 30));

        txtSqrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSqrtActionPerformed(evt);
            }
        });
        getContentPane().add(txtSqrt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 130, 30));

        jLabel4.setFont(new java.awt.Font("Consolas", 3, 18)); // NOI18N
        jLabel4.setText("Căn bậc 2:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, 30));

        txtExponential.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtExponentialActionPerformed(evt);
            }
        });
        getContentPane().add(txtExponential, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, 130, 30));

        jLabel5.setFont(new java.awt.Font("Consolas", 3, 18)); // NOI18N
        jLabel5.setText("Lũy thừa:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, -1, 30));

        txtMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMinActionPerformed(evt);
            }
        });
        getContentPane().add(txtMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 130, 30));

        jLabel6.setFont(new java.awt.Font("Consolas", 3, 18)); // NOI18N
        jLabel6.setText("Số nhỏ nhất:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, 30));

        txtMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaxActionPerformed(evt);
            }
        });
        getContentPane().add(txtMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, 130, 30));

        jLabel7.setFont(new java.awt.Font("Consolas", 3, 18)); // NOI18N
        jLabel7.setText("Số lớn nhất:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, -1, 30));

        btnKq.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnKq.setText("Thực hiện");
        btnKq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKqActionPerformed(evt);
            }
        });
        getContentPane().add(btnKq, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, 120, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAActionPerformed


    }//GEN-LAST:event_txtAActionPerformed

    private void txtBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBActionPerformed

    }//GEN-LAST:event_txtBActionPerformed

    private void txtSqrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSqrtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSqrtActionPerformed

    private void txtExponentialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtExponentialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtExponentialActionPerformed

    private void txtMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMinActionPerformed

    private void txtMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaxActionPerformed

    private void btnKqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKqActionPerformed

        try {
            try {
                if (txtA.getText().equals("") || txtB.getText().equals("")) {
                    JOptionPane.showMessageDialog(this, "Hãy nhập dữ liệu !", "Thông báo", JOptionPane.WARNING_MESSAGE);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Hãy nhập số nguyên !", "Thông báo", JOptionPane.WARNING_MESSAGE);
            }

            double a = Double.parseDouble(txtA.getText());
            double b = Double.parseDouble(txtB.getText());
            double sqrtA = Math.sqrt(a);
            txtSqrt.setText(String.valueOf(sqrtA));
            double powA = Math.pow(a, b);
            txtExponential.setText(String.valueOf(powA));
            double max = Math.max(a, b);
            txtMax.setText(String.valueOf(max));
            
            double min = Math.min(a, b);
            txtMin.setText(String.valueOf(min));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi dữ liệu !", "Thông báo", JOptionPane.WARNING_MESSAGE);

        }


    }//GEN-LAST:event_btnKqActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lab7Bai3Jfram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lab7Bai3Jfram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lab7Bai3Jfram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lab7Bai3Jfram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lab7Bai3Jfram().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKq;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtA;
    private javax.swing.JTextField txtB;
    private javax.swing.JTextField txtExponential;
    private javax.swing.JTextField txtMax;
    private javax.swing.JTextField txtMin;
    private javax.swing.JTextField txtSqrt;
    // End of variables declaration//GEN-END:variables
}
