/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ph26495_ktlab8;

import java.awt.Color;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HL COMPUTER
 */
public class QLLuong extends javax.swing.JFrame {

    ArrayList<SinhVien> listSv = new ArrayList<>();
    int index;

    public QLLuong() {
        initComponents();
        listSv.add(new SinhVien("Le van a",8000000,"TMDT"));
        listSv.add(new SinhVien("Le van b",12000000,"CNTT"));
        listSv.add(new SinhVien("Le van c",25000000,"MKT"));
        findToTable();
        showData(index);
    }

    public void insert() {

        try {
            if (txtName.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Hãy nhập tên!");

            } else if (txtSalary.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Hãy nhập lương!");

            } else if (Double.parseDouble(txtSalary.getText().toString()) < 0) {
                JOptionPane.showMessageDialog(this, "Hãy nhập lương lớn hơn 0!");

            } else {
                SinhVien sinhVien = new SinhVien();
                sinhVien.setName(txtName.getText().toString());
                sinhVien.setSalary(Double.parseDouble(txtSalary.getText().toString()));
                sinhVien.setKhoa((String) cboKhoa.getSelectedItem());
                listSv.add(sinhVien);
                findToTable();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Hãy nhập lương là số!");
        }
    }

    public void findToTable() {
        DefaultTableModel model = (DefaultTableModel) lblSinhVien.getModel();
        model.setRowCount(0);
        for (SinhVien sv : listSv) {
            Object[] obj = new Object[]{
                sv.getName(), sv.getSalary(), sv.getKhoa(), sv.xepLoai(sv.getSalary())
            };
            model.addRow(obj);
        }
    }

    public void showData(int index) {
        txtName.setText((String) lblSinhVien.getValueAt(index, 0));
        txtSalary.setText(lblSinhVien.getValueAt(index, 1) + "");
        cboKhoa.setSelectedItem(lblSinhVien.getValueAt(index, 2));
        lblSinhVien.setRowSelectionInterval(index, index);
    }

    public void reset() {
        txtName.setText("");
        txtSalary.setText("");
        cboKhoa.setSelectedIndex(0);

    }

    public void delete() {
        index = lblSinhVien.getSelectedRow();
        listSv.remove(index);
        reset();
        findToTable();
    }

    public void update() {
        index = lblSinhVien.getSelectedRow();
        SinhVien sv = listSv.get(index);
        sv.setName(txtName.getText().toString());
        sv.setSalary(Double.parseDouble(txtSalary.getText().toString()));
        sv.setKhoa((String) cboKhoa.getSelectedItem());
        findToTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSalary = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        cboKhoa = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        lblSinhVien = new javax.swing.JTable();
        btnUpdate = new javax.swing.JButton();
        btnDoc = new javax.swing.JButton();
        btnGhi = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 0));
        jLabel1.setText("Quản lí đánh giá lương");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel2.setText("Khoa");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel3.setText("Họ và tên");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel4.setText("Lương");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));
        getContentPane().add(txtSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 220, 30));
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 220, 30));

        cboKhoa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CNTT", "MKT", "TMDT", "TKDH" }));
        cboKhoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboKhoaActionPerformed(evt);
            }
        });
        getContentPane().add(cboKhoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 90, 30));

        lblSinhVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Họ tên", "Lương ", "Khoa", "Xếp loại"
            }
        ));
        lblSinhVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSinhVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lblSinhVien);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 550, 200));

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, 80, 30));

        btnDoc.setText("Đọc");
        btnDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocActionPerformed(evt);
            }
        });
        getContentPane().add(btnDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 80, 30));

        btnGhi.setText("Ghi");
        btnGhi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGhiActionPerformed(evt);
            }
        });
        getContentPane().add(btnGhi, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, 80, 30));

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        getContentPane().add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 80, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboKhoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboKhoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboKhoaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        delete();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void lblSinhVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSinhVienMouseClicked
        index = lblSinhVien.getSelectedRow();
        showData(index);
    }//GEN-LAST:event_lblSinhVienMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        update();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnGhiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGhiActionPerformed
     
        try {
               insert();
            ObjectOutputStream oos = new ObjectOutputStream(new FileOutputStream("lab8.txt")) ;
            oos.writeObject(listSv);
            oos.flush();
            oos.close();
        
        } catch (FileNotFoundException ex) {
            Logger.getLogger(QLLuong.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(QLLuong.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_btnGhiActionPerformed

    private void btnDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocActionPerformed
        try {
            
            ObjectInputStream ois = new ObjectInputStream(new FileInputStream("lab8.txt"));
            listSv = (ArrayList<SinhVien>) ois.readObject();
            findToTable();
            showData(listSv.size() - 1);
            ois.close();
        
        } catch (FileNotFoundException ex) {
            Logger.getLogger(QLLuong.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(QLLuong.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(QLLuong.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDocActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLLuong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLLuong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLLuong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLLuong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLLuong().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDoc;
    private javax.swing.JButton btnGhi;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cboKhoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable lblSinhVien;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSalary;
    // End of variables declaration//GEN-END:variables
}
